/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.olmo.GUI.Modificar;

import com.olmo.GUI.Corredores;
import com.olmo.GUI.Principal;
import com.olmo.logica.Operaciones;
import com.olmo.negocio.Carreras.Carrera;
import com.olmo.negocio.Corredores.Corredor;
import com.olmo.negocio.Corredores.Dorsal;
import java.util.ArrayList;
import java.sql.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author OLMO
 */
public class ModificarCarrera extends javax.swing.JDialog {

    /**
     * Creates new form ModificarCarrera
     */
    Principal principal;
    Operaciones op;
    ModificarCarreras modificarCarreras;
    Integer index;
    Carrera carrera;
    Pattern pattern;
    Matcher m;
    Boolean validNombre, validFecha, validLugar, validMax, validLista;
    Map<Corredor, Dorsal> map;
    DefaultListModel<Corredor> listModel;

    public ModificarCarrera(java.awt.Frame parent, JDialog dialog, Integer index, boolean modal) {
        super(parent, modal);
        this.index = index;
        principal = (Principal) parent;
        modificarCarreras = (ModificarCarreras) dialog;
        carrera = principal.getListaCarreras().get(index);
        op = new Operaciones();
        initComponents();
        
         listModel = new DefaultListModel();
         op.llenarJList(listModel, principal.getListaCorredores());
         jListParticipantes.setModel(listModel);
         jListParticipantes.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        setLocationRelativeTo(null);
        jTextFieldNombre.setText(carrera.getNombre());
        jTextFieldFecha.setText(carrera.getFecha().toString());
        jTextFieldLugar.setText(carrera.getLugar());
        jTextFieldMax.setText(carrera.getMaxPart().toString());
        

        map = carrera.getCorredores();
        jLabelCorredoresActualesLlenar.setText(op.corredoresToString(map));

        validNombre = validMax = validFecha = validLugar = true;
        jLabelErrorNombre.setVisible(false);
        jLabelErrorFecha.setVisible(false);
        jLabelErrorLugar.setVisible(false);
        jLabelErrorMax.setVisible(false);
        jLabelErrorLista.setVisible(false);
        jLabelErrores.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonModificar = new javax.swing.JButton();
        jLabelErrorNombre = new javax.swing.JLabel();
        jLabelErrorFecha = new javax.swing.JLabel();
        jLabelLugar = new javax.swing.JLabel();
        jLabelMax = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelErrorLugar = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelErrores = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldLugar = new javax.swing.JTextField();
        jTextFieldMax = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListParticipantes = new javax.swing.JList<>();
        jLabelListaç = new javax.swing.JLabel();
        jLabelErrorLista = new javax.swing.JLabel();
        jLabelErrorMax = new javax.swing.JLabel();
        jLabelCorredoresActuales = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCorredoresActualesLlenar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonModificar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonModificarMouseClicked(evt);
            }
        });

        jLabelErrorNombre.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabelErrorNombre.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorNombre.setText("Rellena el nombre");

        jLabelErrorFecha.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabelErrorFecha.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorFecha.setText("Comprueba el formato 'YYYY-MM-DD'");

        jLabelLugar.setText("Lugar de la carrera:");

        jLabelMax.setText("Máximo de Participantes:");

        jLabelNombre.setText("Nombre: ");

        jLabelFecha.setText("Fecha de la carrera: ");

        jLabelErrorLugar.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabelErrorLugar.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorLugar.setText("Rellena la dirección ");

        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });

        jLabelErrores.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrores.setText("Revisa tus datos, hay errores");

        jTextFieldFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFechaFocusLost(evt);
            }
        });

        jTextFieldLugar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLugarFocusLost(evt);
            }
        });

        jTextFieldMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldMaxFocusLost(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Modificar Carrera");

        jListParticipantes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListParticipantesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListParticipantes);

        jLabelListaç.setText("Lista de participantes:");

        jLabelErrorLista.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabelErrorLista.setForeground(new java.awt.Color(255, 0, 51));
        jLabelErrorLista.setText("Selecciona almenos un corredor");

        jLabelErrorMax.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabelErrorMax.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorMax.setText("Escribe un número entre 1 y 20");

        jLabelCorredoresActuales.setText("Corredores Actuales:");

        jLabelCorredoresActualesLlenar.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabelErrores))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFecha)
                                    .addComponent(jLabelLugar)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelMax)
                                    .addComponent(jLabelCorredoresActuales))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldMax, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelErrorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelErrorLugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(7, 7, 7)
                                                        .addComponent(jLabelErrorLista))))
                                            .addComponent(jLabelErrorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelErrorMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCorredoresActualesLlenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabelListaç, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelErrorNombre)
                            .addComponent(jLabelNombre))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelFecha)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLugar)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrorFecha))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrorLugar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrorMax)
                            .addComponent(jLabelMax))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabelErrorLista)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelListaç)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCorredoresActuales)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCorredoresActualesLlenar))
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addComponent(jButtonModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelErrores)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModificarMouseClicked
        if (validNombre && validFecha && validLugar && validMax && validLista) {
            List<Corredor> listaCorredoresSelect ;
            String raw = jTextFieldFecha.getText();
            String[] arr = raw.split("-");
            for (int i = 0; i < arr.length; i++) {
                System.out.println(arr[i]);
            }
            /*                          Año                  mes                         dia        */
            Date date = new Date(Integer.parseInt(arr[0]) - 1900, Integer.parseInt(arr[1]) - 1, Integer.parseInt(arr[2]));
             listaCorredoresSelect = jListParticipantes.getSelectedValuesList();
             map.clear();
            for(int i = 0;i<listaCorredoresSelect.size();i++){
                map.put(listaCorredoresSelect.get(i),new Dorsal(0,0));
            }
            
            Carrera carrera = new Carrera(jTextFieldNombre.getText(), date, jTextFieldLugar.getText(),
                    Integer.parseInt(jTextFieldMax.getText()), map);
            System.out.println(carrera);
            System.out.println(principal.getListaCarreras());
            op.modificarCarrera(carrera, principal.getListaCarreras(), index);
            op.anadirCarreras(principal.getDtm(), principal.getListaCarreras(), modificarCarreras.getjTableCarreras());

            this.dispose();
        } else {
            jLabelErrores.setVisible(true);
        }
    }//GEN-LAST:event_jButtonModificarMouseClicked

    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        if (jTextFieldNombre.getText().isEmpty()) {
            validNombre = false;
            jLabelErrorNombre.setVisible(true);
        } else {
            validNombre = true;
            jLabelErrorNombre.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldNombreFocusLost

    private void jTextFieldFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFechaFocusLost
        pattern = Pattern.compile("([0-9]{4}-[0-9]{2}-[0-9]{2})");
        m = pattern.matcher(jTextFieldFecha.getText());
        String[] attr = jTextFieldFecha.getText().split("-");

        if (!m.matches() || ((Integer.parseInt(attr[0]) < 0 || Integer.parseInt(attr[0]) > 2020)
                || (Integer.parseInt(attr[1]) < 1 || Integer.parseInt(attr[1]) > 12)
                || (Integer.parseInt(attr[2]) < 1 || Integer.parseInt(attr[2]) > 31))) {
            validFecha = false;
            jLabelErrorFecha.setVisible(true);
        } else {
            validFecha = true;
            jLabelErrorFecha.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldFechaFocusLost

    private void jTextFieldLugarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLugarFocusLost
        if (jTextFieldLugar.getText().isEmpty()) {
            validLugar = false;
            jLabelErrorLugar.setVisible(true);
        } else {
            validLugar = true;
            jLabelErrorLugar.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldLugarFocusLost

    private void jTextFieldMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMaxFocusLost
        pattern = Pattern.compile("([0-9]{2})");
        m = pattern.matcher(jTextFieldMax.getText());
        if (!m.matches() && Integer.parseInt(jTextFieldMax.getText()) < 21) {
            validMax = false;
            jLabelErrorMax.setVisible(true);
        } else {
            validMax = true;
            jLabelErrorMax.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldMaxFocusLost

    private void jListParticipantesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListParticipantesValueChanged
        if (jListParticipantes.getSelectedIndex() == -1) {
            jLabelErrorLista.setVisible(true);
            validLista = false;
        } else {
            validLista = true;
            jLabelErrorLista.setVisible(false);
        }
    }//GEN-LAST:event_jListParticipantesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarCarrera dialog = new ModificarCarrera(new javax.swing.JFrame(), new JDialog(), 0, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCorredoresActuales;
    private javax.swing.JLabel jLabelCorredoresActualesLlenar;
    private javax.swing.JLabel jLabelErrorFecha;
    private javax.swing.JLabel jLabelErrorLista;
    private javax.swing.JLabel jLabelErrorLugar;
    private javax.swing.JLabel jLabelErrorMax;
    private javax.swing.JLabel jLabelErrorNombre;
    private javax.swing.JLabel jLabelErrores;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelListaç;
    private javax.swing.JLabel jLabelLugar;
    private javax.swing.JLabel jLabelMax;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<Corredor> jListParticipantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldLugar;
    private javax.swing.JTextField jTextFieldMax;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
