/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.olmo.GUI;

import com.olmo.GUI.Alta.AltaCarreras;
import com.olmo.GUI.Baja.BajaCorredores;
import com.olmo.GUI.Alta.AltaCorredores;
import com.olmo.GUI.Modificar.ModificarCorredores;
import com.olmo.logica.Operaciones;
import com.olmo.negocio.Carreras.Carrera;
import com.olmo.negocio.Corredores.Corredor;
import com.olmo.negocio.Corredores.Dorsal;
import java.util.ArrayList;
import java.sql.Date;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OLMO
 */
public class Principal extends javax.swing.JFrame {
 Corredores corredores;
 AltaCorredores altaCorredores;
 BajaCorredores bajaCorredores;
  ModificarCorredores  modificarCorredores;
    /**
     * Creates new form Principal
     */
  
     private ArrayList<Carrera> lista;
     private DefaultTableModel dtm;
     Operaciones op;
     AltaCarreras altaCarreras;
    public Principal() {
        initComponents();
        corredores = new Corredores(this,true);
        op=new Operaciones();
         setLocationRelativeTo(null);
         Corredor  corredor =new Corredor("Olmo","71729223C",new Date(99,05,28),"C/Falsa 123",608013779);
         Dorsal dorsal = new Dorsal(60,73);
         Map<Corredor,Dorsal> map =new LinkedHashMap<Corredor,Dorsal>();
         map.put(corredor, dorsal);
       
         Carrera c = new Carrera("Clásica de Boonta Eve", new Date(99,04,19),"Tatooine",10,map,map);
         lista=new ArrayList<Carrera>();
       op.anadirCarrera(c, lista);
         op.inicializarTablaCarrera(dtm,jTableCarreras);
        op.anadirCarreras(dtm, lista, jTableCarreras);
         
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarreras = new javax.swing.JTable();
        jButtonBajaCarreras = new javax.swing.JButton();
        jButtonModificarCarreras = new javax.swing.JButton();
        jButtonAltaCarreras = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCorredores = new javax.swing.JMenu();
        jMenuAltaCorredor = new javax.swing.JMenu();
        jMenuBajaCorredor = new javax.swing.JMenu();
        jMenuModificarCorredor = new javax.swing.JMenu();
        jMenuVerCorredores = new javax.swing.JMenu();
        jMenuCarreras = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Carrera");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Carreras No Realizadas");

        jTableCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha de la carrera", "Lugar de la carrera", "Número máximo de participantes", "Corredores"
            }
        ));
        jScrollPane1.setViewportView(jTableCarreras);

        jButtonBajaCarreras.setText("Baja");

        jButtonModificarCarreras.setText("Modificar");

        jButtonAltaCarreras.setText("Alta");
        jButtonAltaCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAltaCarrerasMouseClicked(evt);
            }
        });

        jMenuCorredores.setText("Corredores");
        jMenuCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCorredoresActionPerformed(evt);
            }
        });

        jMenuAltaCorredor.setText("Alta");
        jMenuAltaCorredor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAltaCorredorMouseClicked(evt);
            }
        });
        jMenuCorredores.add(jMenuAltaCorredor);

        jMenuBajaCorredor.setText("Baja");
        jMenuBajaCorredor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBajaCorredorMouseClicked(evt);
            }
        });
        jMenuCorredores.add(jMenuBajaCorredor);

        jMenuModificarCorredor.setText("Modificar");
        jMenuModificarCorredor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuModificarCorredorMouseClicked(evt);
            }
        });
        jMenuCorredores.add(jMenuModificarCorredor);

        jMenuVerCorredores.setText("Ver Corredores");
        jMenuVerCorredores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVerCorredoresMouseClicked(evt);
            }
        });
        jMenuCorredores.add(jMenuVerCorredores);

        jMenuBar1.add(jMenuCorredores);

        jMenuCarreras.setText("Carreras realizadas");
        jMenuBar1.add(jMenuCarreras);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAltaCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonBajaCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonModificarCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBajaCarreras)
                    .addComponent(jButtonModificarCarreras)
                    .addComponent(jButtonAltaCarreras))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCorredoresActionPerformed
      
    }//GEN-LAST:event_jMenuCorredoresActionPerformed

    private void jMenuVerCorredoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVerCorredoresMouseClicked
        
       corredores.setVisible(true);
    }//GEN-LAST:event_jMenuVerCorredoresMouseClicked

    private void jMenuAltaCorredorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAltaCorredorMouseClicked
      
        altaCorredores = new AltaCorredores(this,corredores,true);
       altaCorredores.setVisible(true);
    }//GEN-LAST:event_jMenuAltaCorredorMouseClicked

    private void jMenuBajaCorredorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBajaCorredorMouseClicked
        bajaCorredores = new BajaCorredores(this,corredores,true);
       bajaCorredores.setVisible(true);
    }//GEN-LAST:event_jMenuBajaCorredorMouseClicked

    private void jMenuModificarCorredorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuModificarCorredorMouseClicked
         modificarCorredores = new ModificarCorredores(this,corredores,true);
       modificarCorredores.setVisible(true);
    }//GEN-LAST:event_jMenuModificarCorredorMouseClicked

    private void jButtonAltaCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAltaCarrerasMouseClicked
       altaCarreras = new AltaCarreras(this,true);
       altaCarreras.setVisible(true);
    }//GEN-LAST:event_jButtonAltaCarrerasMouseClicked

    public ArrayList<Carrera> getLista() {
        return lista;
    }

    public void setLista(ArrayList<Carrera> lista) {
        this.lista = lista;
    }

    public DefaultTableModel getDtm() {
        return dtm;
    }

    public void setDtm(DefaultTableModel dtm) {
        this.dtm = dtm;
    }

    public JTable getjTableCarreras() {
        return jTableCarreras;
    }

    public void setjTableCarreras(JTable jTableCarreras) {
        this.jTableCarreras = jTableCarreras;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltaCarreras;
    private javax.swing.JButton jButtonBajaCarreras;
    private javax.swing.JButton jButtonModificarCarreras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAltaCorredor;
    private javax.swing.JMenu jMenuBajaCorredor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCarreras;
    private javax.swing.JMenu jMenuCorredores;
    private javax.swing.JMenu jMenuModificarCorredor;
    private javax.swing.JMenu jMenuVerCorredores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCarreras;
    // End of variables declaration//GEN-END:variables
}
